// <auto-generated />
using HotDrinks.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotDrinks.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231105194306_UpdateHotDrinkActions")]
    partial class UpdateHotDrinkActions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("HotDrinkHotDrinkAction", b =>
                {
                    b.Property<int>("ActionsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DrinksId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ActionsId", "DrinksId");

                    b.HasIndex("DrinksId");

                    b.ToTable("HotDrinkHotDrinkAction");
                });

            modelBuilder.Entity("HotDrinks.Models.HotDrink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("HotDrinks");
                });

            modelBuilder.Entity("HotDrinks.Models.HotDrinkAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("HotDrinkActions");
                });

            modelBuilder.Entity("HotDrinkHotDrinkAction", b =>
                {
                    b.HasOne("HotDrinks.Models.HotDrinkAction", null)
                        .WithMany()
                        .HasForeignKey("ActionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotDrinks.Models.HotDrink", null)
                        .WithMany()
                        .HasForeignKey("DrinksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
